stages:
  - test
  - deploy

deploy:
  stage: deploy
  only:
  - master
  image: google/cloud-sdk:alpine
  environment: Production
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud app deploy app.yaml --quiet --project $PROJECT_ID 
  - gcloud app deploy dispatch.yaml --project $PROJECT_ID 
  after_script:
  - rm /tmp/$CI_PIPELINE_ID.json

test:
  stage: test
  only:
    - master
    - test
  image: node:21.1-alpine
  before_script:
    - if [ ! -d  node_modules ]; then yarn install; fi
  script:
    - CI=true
    - yarn test -- --ci --passWithNoTests
